mqtt:
  host: 192.168.1.50
  port: 8883
  tls: true
  username: sensehat_node
  password: "<SECRET>"
  namespace: spBv1.0
  group: sensehat
  edge_node: pi-edge
  publish_period_s: 2
http:
  bind: 0.0.0.0
  port: 8080
sensors:
  enable_accel: true
  enable_env: true
  cpu_temp: true
node_red:
  enable: true
  url: http://<pi-ip>:1880
security:
  ufw:
    allow:
      - 22
      - 8080
      - 1880
